from . import ssh_utils
from . import odoo_version
from . import partner_asset
from . import partner_hosting_provider
from . import partner_infrastructure
from . import partner_environment_platform
from . import partner_environment
from . import res_partner
from . import res_config_settings
from . import account_move
from . import partner_asset_stage
from . import partner_asset_custom_module
from . import partner_asset_tag
from . import partner_asset_native_module
from . import partner_asset_credential_log
from . import infrastructure_command_wizard
from . import sale_order
from . import project_task
from . import utm_campaign
from . import project_template_task
from . import project_template_wizard
from . import project_template_import_wizard
from . import sale_offer_wizard
from . import partner_asset_task_link_wizard
from . import demo_import_wizard
