{
    'name': 'Odoo Clients 360',
    'version': '19.0.5',
    'category': 'Sales',
    'summary': 'All-in-One Client Asset, Service & Financial Hub for Odoo Partners',
    'description': """
        Odoo Clients 360 is a comprehensive management dashboard for Odoo Partners and IT Service Providers.
        Track domains, hosting, SSL, Git, and server details with live SSL & uptime monitoring.
        Monitor infrastructure costs, client billing, and margins with a financial dashboard.
        Encrypted credential storage with access audit log, role-based access control,
        automated expiry notifications with email reminders and weekly manager digest,
        renewal quotations with automatic date extension on confirmation,
        client portal access, per-client infrastructure PDF reports, calendar view,
        project task integration, tags, and multi-company support.
    """,
    'author': 'Techman Solutions, Mirsad Selimovic',
    'website': 'https://www.techman.qa',
    'maintainer': 'Mirsad Selimovic',
    'support': 'odoo@techman.qa',
    'depends': ['base', 'mail', 'sale', 'portal', 'project', 'utm'],
    'external_dependencies': {
        'python': ['cryptography'],
    },
    'data': [
        'security/security_groups.xml',
        'security/security_rules.xml',
        'data/ir_cron_data.xml',
        'data/ir_cron_health_digest.xml',
        'data/ir_sequence_data.xml',
        'data/mail_template_data.xml',
        'data/product_data.xml',
        'data/partner_asset_stage_data.xml',
        'data/partner_asset_tag_data.xml',
        'data/partner_asset_native_module_data.xml',
        'data/project_data.xml',
        'data/project_template_task_data.xml',
        'views/partner_asset_stage_views.xml',
        'views/partner_asset_views.xml',
        'views/utm_campaign_views.xml',
        'views/project_task_views.xml',
        'views/project_template_task_views.xml',
        'views/project_template_wizard_views.xml',
        'views/sale_offer_wizard_views.xml',
        'views/partner_asset_tag_views.xml',
        'views/partner_asset_native_module_views.xml',
        'views/partner_infrastructure_views.xml',
        'views/res_partner_views.xml',
        'views/demo_import_wizard_views.xml',
        'views/portal_templates.xml',
        'report/report_client_infrastructure.xml',
        'report/report_client_credentials.xml',
        'security/ir.model.access.csv',
    ],
    'assets': {
        'web.assets_backend': [
            'ts_partner_app/static/src/dashboard/client_hub_dashboard.js',
            'ts_partner_app/static/src/dashboard/client_hub_dashboard.xml',
            'ts_partner_app/static/src/dashboard/client_hub_dashboard.scss',
        ],
    },
    'images': [
        'static/description/banner.jpg',
        'static/screenshots/Screenshot 2026-08-20 at 21.17.19.png',
        'static/screenshots/Screenshot 2026-08-20 at 21.17.37.png',
        'static/screenshots/Screenshot 2026-08-20 at 21.18.05.png',
        'static/screenshots/Screenshot 2026-08-20 at 21.17.55.png',
    ],
    'application': True,
    'installable': True,
    'license': 'LGPL-3',
}
